---
abstract: 'Use DeveloperGarden APIs from Perl'
author:
  - 'Renee Baecker <reneeb@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300037, CPAN::Meta::Converter version 2.132140'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-DeveloperGarden
requires:
  HTTP::Tiny: 0
  JSON: 0
  MIME::Base64: 0
  Moo: 0
  Type::Tiny: 0
version: 0.01
